esphome:
  name: esp32

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "fbb2a0ee32f37c4b2c18cf69cbe7b8f6"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password




sensor:
  - platform: template
    name: "BLE Sensor"
    id: ble_sensor

esp32_ble_tracker:
  on_ble_service_data_advertise:
    - mac_address: E9:5C:F3:80:0B:0F
      service_uuid: "1800"
      then:
        - lambda: 'id(ble_sensor).publish_state(x[0]);'

ble_client:
  - mac_address: E9:5C:F3:80:0B:0F
    id: dexcom

#binary_sensor:
#  - platform: ble_presence
#    mac_address: E9:5C:F3:80:0B:0F
#    name: "Dexcom"

#sensor:
#  - platform: ble_rssi
#    mac_address: E9:5C:F3:80:0B:0F
#    name: "Dexcom RSSI value"