# Sensor on the garage doors to report when one or both are open.
#
substitutions:
  device_name: garage-door
  
esphome:
  name: ${device_name}
  
esp8266:
  board: d1_mini

# Enable logging
# Debug level needed to get 1-Wire addresses, like the ds18b20.
logger:
  level: DEBUG  

# Enable Home Assistant API
api:

ota:
  safe_mode: True

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  
  
#######################################
# Device specific Config Begins Below #
#######################################


######################################
# Blink the LED if there's a problem, on otherwise.    
# The built-in LED is D4 (GPIO2) on the Wemos D1 Mini
status_led:
  pin:
    number: D5
    inverted: True


#####################################
sensor:
  - platform: wifi_signal
    name: ${device_name} Wifi Signal Strength
    update_interval: 60s
    
    
text_sensor:
  # Get the WiFi details
  - platform: wifi_info
    ip_address:
      name: ${device_name} IP Address
    mac_address:
      name: ${device_name} Mac Address


# report the Volt switch to be on when the switch is closed
binary_sensor:
  - platform: gpio
    device_class: garage_door
    pin:
      number: D1
      mode: INPUT_PULLUP
    name: ${device_name} volt
#    on_press:
#      then:
#      - switch.turn_on: volt_led
#    on_release:
#      then:
#      - switch.turn_off: volt_led

# report the Jeep switch to be on when the switch is closed
  - platform: gpio
    device_class: garage_door
    pin:
      number: D2
      mode: INPUT_PULLUP
    name: ${device_name} jeep
#    on_press:
#      then:
#      - switch.turn_on: jeep_led
#    on_release:
#      then:
#      - switch.turn_off: jeep_led
      



# The LEDs on D6 and D7 are Virtual Switches.
#switch:
#  - platform: gpio
#    name: ${device_name} volt LED
#    pin:
#      number: D6
#      mode: output
#    id: volt_led
#    internal: true
    
#  - platform: gpio
#    name: ${device_name} jeep LED
#    pin:
#      number: D7
#      mode: output
#    id: jeep_led
#    internal: true

