esphome:
  name: outside_temperature
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: "Kaywinnet"
  password: !secret wifi_password
  fast_connect: true

#  # Enable fallback hotspot (captive portal) in case wifi connection fails
#  ap:
#    ssid: "Outside Temperature"
#    password: "SPaWmSyjy2r6"
#
#captive_portal:

# Enable logging
# Debug level needed to get Dallas ds18b20 address.
logger:
  level: DEBUG

# Enable Home Assistant API
api:

ota:
  safe_mode: True

######################################
# Blink the LED if there's a problem, off otherwise.    
#status_led:
#  pin:
#    number: D4
#    inverted: True
    
dallas:
  - pin: D4      
    update_interval: 5s    
    
sensor:
  # WiFi Signal sensor.
  - platform: wifi_signal
    name: Outside Temperature WiFi Signal
    update_interval: 60s
 
 
#  #Dallas DS18B20 Temperature sensor  
  - platform: dallas
    address: 0x67020D9246E81C28
    name: "Outside Temperature"
    unit_of_measurement: '°F'
    filters:
    - lambda: return x * (9.0/5.0) + 32.0;
